// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: command_payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandPayload_Configure
	//	*CommandPayload_SetState
	//	*CommandPayload_SetParams
	//	*CommandPayload_GetParams
	//	*CommandPayload_Ping
	Command       isCommandPayload_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandPayload) Reset() {
	*x = CommandPayload{}
	mi := &file_command_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandPayload) ProtoMessage() {}

func (x *CommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandPayload.ProtoReflect.Descriptor instead.
func (*CommandPayload) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{0}
}

func (x *CommandPayload) GetCommand() isCommandPayload_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandPayload) GetConfigure() *CmdConfigure {
	if x != nil {
		if x, ok := x.Command.(*CommandPayload_Configure); ok {
			return x.Configure
		}
	}
	return nil
}

func (x *CommandPayload) GetSetState() *CmdSetState {
	if x != nil {
		if x, ok := x.Command.(*CommandPayload_SetState); ok {
			return x.SetState
		}
	}
	return nil
}

func (x *CommandPayload) GetSetParams() *CmdSetParams {
	if x != nil {
		if x, ok := x.Command.(*CommandPayload_SetParams); ok {
			return x.SetParams
		}
	}
	return nil
}

func (x *CommandPayload) GetGetParams() *CmdGetParams {
	if x != nil {
		if x, ok := x.Command.(*CommandPayload_GetParams); ok {
			return x.GetParams
		}
	}
	return nil
}

func (x *CommandPayload) GetPing() *CmdPing {
	if x != nil {
		if x, ok := x.Command.(*CommandPayload_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isCommandPayload_Command interface {
	isCommandPayload_Command()
}

type CommandPayload_Configure struct {
	Configure *CmdConfigure `protobuf:"bytes,2,opt,name=configure,proto3,oneof"`
}

type CommandPayload_SetState struct {
	SetState *CmdSetState `protobuf:"bytes,3,opt,name=set_state,json=setState,proto3,oneof"`
}

type CommandPayload_SetParams struct {
	SetParams *CmdSetParams `protobuf:"bytes,4,opt,name=set_params,json=setParams,proto3,oneof"`
}

type CommandPayload_GetParams struct {
	GetParams *CmdGetParams `protobuf:"bytes,5,opt,name=get_params,json=getParams,proto3,oneof"`
}

type CommandPayload_Ping struct {
	Ping *CmdPing `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

func (*CommandPayload_Configure) isCommandPayload_Command() {}

func (*CommandPayload_SetState) isCommandPayload_Command() {}

func (*CommandPayload_SetParams) isCommandPayload_Command() {}

func (*CommandPayload_GetParams) isCommandPayload_Command() {}

func (*CommandPayload_Ping) isCommandPayload_Command() {}

// Configuration
//
// It's a kind of macros. With this command one could define a dictionary of
// parameters and values that should be set if device switches to the state.
//
// Example:
// {
// "state_riding": {
// "engine_lock": "disable",
// "scooter_lock": "unlock",
// "dashboard_color": "white",
// "dashboard_effect": "breathing",
// "speed_limit": 25
// },
// "state_service": {
// "engine_lock": "disable",
// "scooter_lock": "unlock",
// "dashboard_color": "red",
// "dashboard_effect": "breathing",
// "speed_limit": 5
// }
// }
type CmdConfigure struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	StateName     string                                    `protobuf:"bytes,1,opt,name=state_name,json=stateName,proto3" json:"state_name,omitempty"`
	States        map[string]*CmdConfigure_StateDescription `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConfigure) Reset() {
	*x = CmdConfigure{}
	mi := &file_command_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConfigure) ProtoMessage() {}

func (x *CmdConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConfigure.ProtoReflect.Descriptor instead.
func (*CmdConfigure) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{1}
}

func (x *CmdConfigure) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

func (x *CmdConfigure) GetStates() map[string]*CmdConfigure_StateDescription {
	if x != nil {
		return x.States
	}
	return nil
}

// Switches an IoT to the particular state.
// The state should be previously defined by the CmdConfigure
type CmdSetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdSetState) Reset() {
	*x = CmdSetState{}
	mi := &file_command_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdSetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdSetState) ProtoMessage() {}

func (x *CmdSetState) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdSetState.ProtoReflect.Descriptor instead.
func (*CmdSetState) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{2}
}

func (x *CmdSetState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Set (change) a couple of parameters
type CmdSetParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdSetParams) Reset() {
	*x = CmdSetParams{}
	mi := &file_command_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdSetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdSetParams) ProtoMessage() {}

func (x *CmdSetParams) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdSetParams.ProtoReflect.Descriptor instead.
func (*CmdSetParams) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{3}
}

func (x *CmdSetParams) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// Get a couple if values from the IoT
type CmdGetParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         []string               `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdGetParams) Reset() {
	*x = CmdGetParams{}
	mi := &file_command_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdGetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetParams) ProtoMessage() {}

func (x *CmdGetParams) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetParams.ProtoReflect.Descriptor instead.
func (*CmdGetParams) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{4}
}

func (x *CmdGetParams) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

// Simple ping message
type CmdPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdPing) Reset() {
	*x = CmdPing{}
	mi := &file_command_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdPing) ProtoMessage() {}

func (x *CmdPing) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdPing.ProtoReflect.Descriptor instead.
func (*CmdPing) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{5}
}

type CmdConfigure_StateDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateParams   map[string]string      `protobuf:"bytes,1,rep,name=state_params,json=stateParams,proto3" json:"state_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConfigure_StateDescription) Reset() {
	*x = CmdConfigure_StateDescription{}
	mi := &file_command_payload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConfigure_StateDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConfigure_StateDescription) ProtoMessage() {}

func (x *CmdConfigure_StateDescription) ProtoReflect() protoreflect.Message {
	mi := &file_command_payload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConfigure_StateDescription.ProtoReflect.Descriptor instead.
func (*CmdConfigure_StateDescription) Descriptor() ([]byte, []int) {
	return file_command_payload_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CmdConfigure_StateDescription) GetStateParams() map[string]string {
	if x != nil {
		return x.StateParams
	}
	return nil
}

var File_command_payload_proto protoreflect.FileDescriptor

const file_command_payload_proto_rawDesc = "" +
	"\n" +
	"\x15command_payload.proto\x12\x11iot.backend.proto\"\xd1\x02\n" +
	"\x0eCommandPayload\x12?\n" +
	"\tconfigure\x18\x02 \x01(\v2\x1f.iot.backend.proto.CmdConfigureH\x00R\tconfigure\x12=\n" +
	"\tset_state\x18\x03 \x01(\v2\x1e.iot.backend.proto.CmdSetStateH\x00R\bsetState\x12@\n" +
	"\n" +
	"set_params\x18\x04 \x01(\v2\x1f.iot.backend.proto.CmdSetParamsH\x00R\tsetParams\x12@\n" +
	"\n" +
	"get_params\x18\x05 \x01(\v2\x1f.iot.backend.proto.CmdGetParamsH\x00R\tgetParams\x120\n" +
	"\x04ping\x18\x06 \x01(\v2\x1a.iot.backend.proto.CmdPingH\x00R\x04pingB\t\n" +
	"\acommand\"\x9a\x03\n" +
	"\fCmdConfigure\x12\x1d\n" +
	"\n" +
	"state_name\x18\x01 \x01(\tR\tstateName\x12C\n" +
	"\x06states\x18\x02 \x03(\v2+.iot.backend.proto.CmdConfigure.StatesEntryR\x06states\x1a\xb8\x01\n" +
	"\x10StateDescription\x12d\n" +
	"\fstate_params\x18\x01 \x03(\v2A.iot.backend.proto.CmdConfigure.StateDescription.StateParamsEntryR\vstateParams\x1a>\n" +
	"\x10StateParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ak\n" +
	"\vStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.iot.backend.proto.CmdConfigure.StateDescriptionR\x05value:\x028\x01\"#\n" +
	"\vCmdSetState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"\x8e\x01\n" +
	"\fCmdSetParams\x12C\n" +
	"\x06params\x18\x01 \x03(\v2+.iot.backend.proto.CmdSetParams.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\fCmdGetParams\x12\x14\n" +
	"\x05param\x18\x01 \x03(\tR\x05param\"\t\n" +
	"\aCmdPingb\x06proto3"

var (
	file_command_payload_proto_rawDescOnce sync.Once
	file_command_payload_proto_rawDescData []byte
)

func file_command_payload_proto_rawDescGZIP() []byte {
	file_command_payload_proto_rawDescOnce.Do(func() {
		file_command_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_payload_proto_rawDesc), len(file_command_payload_proto_rawDesc)))
	})
	return file_command_payload_proto_rawDescData
}

var file_command_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_command_payload_proto_goTypes = []any{
	(*CommandPayload)(nil),                // 0: iot.backend.proto.CommandPayload
	(*CmdConfigure)(nil),                  // 1: iot.backend.proto.CmdConfigure
	(*CmdSetState)(nil),                   // 2: iot.backend.proto.CmdSetState
	(*CmdSetParams)(nil),                  // 3: iot.backend.proto.CmdSetParams
	(*CmdGetParams)(nil),                  // 4: iot.backend.proto.CmdGetParams
	(*CmdPing)(nil),                       // 5: iot.backend.proto.CmdPing
	(*CmdConfigure_StateDescription)(nil), // 6: iot.backend.proto.CmdConfigure.StateDescription
	nil,                                   // 7: iot.backend.proto.CmdConfigure.StatesEntry
	nil,                                   // 8: iot.backend.proto.CmdConfigure.StateDescription.StateParamsEntry
	nil,                                   // 9: iot.backend.proto.CmdSetParams.ParamsEntry
}
var file_command_payload_proto_depIdxs = []int32{
	1, // 0: iot.backend.proto.CommandPayload.configure:type_name -> iot.backend.proto.CmdConfigure
	2, // 1: iot.backend.proto.CommandPayload.set_state:type_name -> iot.backend.proto.CmdSetState
	3, // 2: iot.backend.proto.CommandPayload.set_params:type_name -> iot.backend.proto.CmdSetParams
	4, // 3: iot.backend.proto.CommandPayload.get_params:type_name -> iot.backend.proto.CmdGetParams
	5, // 4: iot.backend.proto.CommandPayload.ping:type_name -> iot.backend.proto.CmdPing
	7, // 5: iot.backend.proto.CmdConfigure.states:type_name -> iot.backend.proto.CmdConfigure.StatesEntry
	9, // 6: iot.backend.proto.CmdSetParams.params:type_name -> iot.backend.proto.CmdSetParams.ParamsEntry
	8, // 7: iot.backend.proto.CmdConfigure.StateDescription.state_params:type_name -> iot.backend.proto.CmdConfigure.StateDescription.StateParamsEntry
	6, // 8: iot.backend.proto.CmdConfigure.StatesEntry.value:type_name -> iot.backend.proto.CmdConfigure.StateDescription
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_command_payload_proto_init() }
func file_command_payload_proto_init() {
	if File_command_payload_proto != nil {
		return
	}
	file_command_payload_proto_msgTypes[0].OneofWrappers = []any{
		(*CommandPayload_Configure)(nil),
		(*CommandPayload_SetState)(nil),
		(*CommandPayload_SetParams)(nil),
		(*CommandPayload_GetParams)(nil),
		(*CommandPayload_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_payload_proto_rawDesc), len(file_command_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_payload_proto_goTypes,
		DependencyIndexes: file_command_payload_proto_depIdxs,
		MessageInfos:      file_command_payload_proto_msgTypes,
	}.Build()
	File_command_payload_proto = out.File
	file_command_payload_proto_goTypes = nil
	file_command_payload_proto_depIdxs = nil
}
