// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: error.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultCode int32

const (
	ResultCode_RESULT_UNSPECIFIED ResultCode = 0 // For protobufs it's a good practice to set a zero item of enum as "unspecified"
	ResultCode_RESULT_SUCCESS     ResultCode = 1
	ResultCode_RESULT_FAILED      ResultCode = 2 // If resource is unavailbale now
)

// Enum value maps for ResultCode.
var (
	ResultCode_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_SUCCESS",
		2: "RESULT_FAILED",
	}
	ResultCode_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"RESULT_SUCCESS":     1,
		"RESULT_FAILED":      2,
	}
)

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ResultCode) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultCode.Descriptor instead.
func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_STATUS_UNSPECIFIED     ErrorCode = 0 // For protobufs it's a good practice to set a zero item of enum as "unspecified"
	ErrorCode_STATUS_OK              ErrorCode = 1 // OK
	ErrorCode_STATUS_NOT_IMPLEMENTED ErrorCode = 2 // The command has not been implemented yet
	ErrorCode_STATUS_UNAVAILABLE     ErrorCode = 3 // If resource is unavailable now
	ErrorCode_STATUS_OUTDATED        ErrorCode = 4 // If the command was received too late (after deadline)
	ErrorCode_STATUS_OTHER           ErrorCode = 5 // Unknown error (see the message in details)
	ErrorCode_STATUS_PACKET_INVALID  ErrorCode = 6 // Packet validation failed
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_NOT_IMPLEMENTED",
		3: "STATUS_UNAVAILABLE",
		4: "STATUS_OUTDATED",
		5: "STATUS_OTHER",
		6: "STATUS_PACKET_INVALID",
	}
	ErrorCode_value = map[string]int32{
		"STATUS_UNSPECIFIED":     0,
		"STATUS_OK":              1,
		"STATUS_NOT_IMPLEMENTED": 2,
		"STATUS_UNAVAILABLE":     3,
		"STATUS_OUTDATED":        4,
		"STATUS_OTHER":           5,
		"STATUS_PACKET_INVALID":  6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

type ErrorDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Status        *ErrorCode             `protobuf:"varint,2,opt,name=status,proto3,enum=iot.backend.proto.ErrorCode,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDescription) Reset() {
	*x = ErrorDescription{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDescription) ProtoMessage() {}

func (x *ErrorDescription) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDescription.ProtoReflect.Descriptor instead.
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDescription) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ErrorDescription) GetStatus() ErrorCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ErrorCode_STATUS_UNSPECIFIED
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\x11iot.backend.proto\"\x83\x01\n" +
	"\x10ErrorDescription\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.iot.backend.proto.ErrorCodeH\x01R\x06status\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_status*K\n" +
	"\n" +
	"ResultCode\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x11\n" +
	"\rRESULT_FAILED\x10\x02*\xa8\x01\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x1a\n" +
	"\x16STATUS_NOT_IMPLEMENTED\x10\x02\x12\x16\n" +
	"\x12STATUS_UNAVAILABLE\x10\x03\x12\x13\n" +
	"\x0fSTATUS_OUTDATED\x10\x04\x12\x10\n" +
	"\fSTATUS_OTHER\x10\x05\x12\x19\n" +
	"\x15STATUS_PACKET_INVALID\x10\x06b\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_error_proto_goTypes = []any{
	(ResultCode)(0),          // 0: iot.backend.proto.ResultCode
	(ErrorCode)(0),           // 1: iot.backend.proto.ErrorCode
	(*ErrorDescription)(nil), // 2: iot.backend.proto.ErrorDescription
}
var file_error_proto_depIdxs = []int32{
	1, // 0: iot.backend.proto.ErrorDescription.status:type_name -> iot.backend.proto.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	file_error_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
