// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: notification_payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPayload) Reset() {
	*x = NotificationPayload{}
	mi := &file_notification_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPayload) ProtoMessage() {}

func (x *NotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_notification_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPayload.ProtoReflect.Descriptor instead.
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return file_notification_payload_proto_rawDescGZIP(), []int{0}
}

var File_notification_payload_proto protoreflect.FileDescriptor

const file_notification_payload_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_payload.proto\x12\x11iot.backend.proto\"\x15\n" +
	"\x13NotificationPayloadb\x06proto3"

var (
	file_notification_payload_proto_rawDescOnce sync.Once
	file_notification_payload_proto_rawDescData []byte
)

func file_notification_payload_proto_rawDescGZIP() []byte {
	file_notification_payload_proto_rawDescOnce.Do(func() {
		file_notification_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_payload_proto_rawDesc), len(file_notification_payload_proto_rawDesc)))
	})
	return file_notification_payload_proto_rawDescData
}

var file_notification_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_payload_proto_goTypes = []any{
	(*NotificationPayload)(nil), // 0: iot.backend.proto.NotificationPayload
}
var file_notification_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_payload_proto_init() }
func file_notification_payload_proto_init() {
	if File_notification_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_payload_proto_rawDesc), len(file_notification_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_payload_proto_goTypes,
		DependencyIndexes: file_notification_payload_proto_depIdxs,
		MessageInfos:      file_notification_payload_proto_msgTypes,
	}.Build()
	File_notification_payload_proto = out.File
	file_notification_payload_proto_goTypes = nil
	file_notification_payload_proto_depIdxs = nil
}
