// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: packet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Version    uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                               // 4-bytes of version. 2 high bytes - major version, 2 lower bytes - minor part.
	Timestamp  uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Timestamp in seconds since Epoch (UTC)
	ValidUntil *uint64                `protobuf:"varint,3,opt,name=valid_until,json=validUntil,proto3,oneof" json:"valid_until,omitempty"` // Command deadline in seconds since Epoch (UTC).
	// Чтобы добавить поддержку нового типа пакета, ищи тэг #ADD_NEW_PACKET и делай,
	// как там написано
	//
	// Types that are valid to be assigned to What:
	//
	//	*Packet_Command
	//	*Packet_CommandResult
	//	*Packet_Telemetry
	//	*Packet_Request
	//	*Packet_Response
	//	*Packet_Notification
	What          isPacket_What `protobuf_oneof:"what"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Packet) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Packet) GetValidUntil() uint64 {
	if x != nil && x.ValidUntil != nil {
		return *x.ValidUntil
	}
	return 0
}

func (x *Packet) GetWhat() isPacket_What {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *Packet) GetCommand() *Command {
	if x != nil {
		if x, ok := x.What.(*Packet_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Packet) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.What.(*Packet_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *Packet) GetTelemetry() *Telemetry {
	if x != nil {
		if x, ok := x.What.(*Packet_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x != nil {
		if x, ok := x.What.(*Packet_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x != nil {
		if x, ok := x.What.(*Packet_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Packet) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.What.(*Packet_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isPacket_What interface {
	isPacket_What()
}

type Packet_Command struct {
	Command *Command `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type Packet_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,5,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type Packet_Telemetry struct {
	Telemetry *Telemetry `protobuf:"bytes,6,opt,name=telemetry,proto3,oneof"`
}

type Packet_Request struct {
	Request *Request `protobuf:"bytes,7,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,8,opt,name=response,proto3,oneof"`
}

type Packet_Notification struct {
	Notification *Notification `protobuf:"bytes,9,opt,name=notification,proto3,oneof"`
}

func (*Packet_Command) isPacket_What() {}

func (*Packet_CommandResult) isPacket_What() {}

func (*Packet_Telemetry) isPacket_What() {}

func (*Packet_Request) isPacket_What() {}

func (*Packet_Response) isPacket_What() {}

func (*Packet_Notification) isPacket_What() {}

// A testing packet to check backward compatibility of the protocol
// We are expecting, given:
//
// Packet.v1 (1 optional field) and Packet.v2 (2 optional fields)
// Consider both versions having values for all their properties set.
//
// - Packet.v1 -> Packet.v2 (binary, json)
// - Packet.v2 -> Packet.v1 (binary)
// IMPORTANT!!! - JSON.v2 -> Packet.v1 will fail in this case
type PacketTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketTest) Reset() {
	*x = PacketTest{}
	mi := &file_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketTest) ProtoMessage() {}

func (x *PacketTest) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketTest.ProtoReflect.Descriptor instead.
func (*PacketTest) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1}
}

func (x *PacketTest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PacketTest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_packet_proto protoreflect.FileDescriptor

const file_packet_proto_rawDesc = "" +
	"\n" +
	"\fpacket.proto\x12\x11iot.backend.proto\x1a\rcommand.proto\x1a\x14command_result.proto\x1a\x0ftelemetry.proto\x1a\rrequest.proto\x1a\x0eresponse.proto\x1a\x12notification.proto\"\xf9\x03\n" +
	"\x06Packet\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12$\n" +
	"\vvalid_until\x18\x03 \x01(\x04H\x01R\n" +
	"validUntil\x88\x01\x01\x126\n" +
	"\acommand\x18\x04 \x01(\v2\x1a.iot.backend.proto.CommandH\x00R\acommand\x12I\n" +
	"\x0ecommand_result\x18\x05 \x01(\v2 .iot.backend.proto.CommandResultH\x00R\rcommandResult\x12<\n" +
	"\ttelemetry\x18\x06 \x01(\v2\x1c.iot.backend.proto.TelemetryH\x00R\ttelemetry\x126\n" +
	"\arequest\x18\a \x01(\v2\x1a.iot.backend.proto.RequestH\x00R\arequest\x129\n" +
	"\bresponse\x18\b \x01(\v2\x1b.iot.backend.proto.ResponseH\x00R\bresponse\x12E\n" +
	"\fnotification\x18\t \x01(\v2\x1f.iot.backend.proto.NotificationH\x00R\fnotificationB\x06\n" +
	"\x04whatB\x0e\n" +
	"\f_valid_until\"D\n" +
	"\n" +
	"PacketTest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestampb\x06proto3"

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData []byte
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)))
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packet_proto_goTypes = []any{
	(*Packet)(nil),        // 0: iot.backend.proto.Packet
	(*PacketTest)(nil),    // 1: iot.backend.proto.PacketTest
	(*Command)(nil),       // 2: iot.backend.proto.Command
	(*CommandResult)(nil), // 3: iot.backend.proto.CommandResult
	(*Telemetry)(nil),     // 4: iot.backend.proto.Telemetry
	(*Request)(nil),       // 5: iot.backend.proto.Request
	(*Response)(nil),      // 6: iot.backend.proto.Response
	(*Notification)(nil),  // 7: iot.backend.proto.Notification
}
var file_packet_proto_depIdxs = []int32{
	2, // 0: iot.backend.proto.Packet.command:type_name -> iot.backend.proto.Command
	3, // 1: iot.backend.proto.Packet.command_result:type_name -> iot.backend.proto.CommandResult
	4, // 2: iot.backend.proto.Packet.telemetry:type_name -> iot.backend.proto.Telemetry
	5, // 3: iot.backend.proto.Packet.request:type_name -> iot.backend.proto.Request
	6, // 4: iot.backend.proto.Packet.response:type_name -> iot.backend.proto.Response
	7, // 5: iot.backend.proto.Packet.notification:type_name -> iot.backend.proto.Notification
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	file_command_proto_init()
	file_command_result_proto_init()
	file_telemetry_proto_init()
	file_request_proto_init()
	file_response_proto_init()
	file_notification_proto_init()
	file_packet_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Command)(nil),
		(*Packet_CommandResult)(nil),
		(*Packet_Telemetry)(nil),
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
		(*Packet_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
