// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChainId string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Result  ResultCode             `protobuf:"varint,2,opt,name=result,proto3,enum=iot.backend.proto.ResultCode" json:"result,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Response_ErrorDescription
	//	*Response_Payload
	Details       isResponse_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Response) GetResult() ResultCode {
	if x != nil {
		return x.Result
	}
	return ResultCode_RESULT_UNSPECIFIED
}

func (x *Response) GetDetails() isResponse_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Response) GetErrorDescription() *ErrorDescription {
	if x != nil {
		if x, ok := x.Details.(*Response_ErrorDescription); ok {
			return x.ErrorDescription
		}
	}
	return nil
}

func (x *Response) GetPayload() *ResponsePayload {
	if x != nil {
		if x, ok := x.Details.(*Response_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isResponse_Details interface {
	isResponse_Details()
}

type Response_ErrorDescription struct {
	ErrorDescription *ErrorDescription `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3,oneof"`
}

type Response_Payload struct {
	Payload *ResponsePayload `protobuf:"bytes,4,opt,name=payload,proto3,oneof"`
}

func (*Response_ErrorDescription) isResponse_Details() {}

func (*Response_Payload) isResponse_Details() {}

var File_response_proto protoreflect.FileDescriptor

const file_response_proto_rawDesc = "" +
	"\n" +
	"\x0eresponse.proto\x12\x11iot.backend.proto\x1a\verror.proto\x1a\x16response_payload.proto\"\xfb\x01\n" +
	"\bResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x125\n" +
	"\x06result\x18\x02 \x01(\x0e2\x1d.iot.backend.proto.ResultCodeR\x06result\x12R\n" +
	"\x11error_description\x18\x03 \x01(\v2#.iot.backend.proto.ErrorDescriptionH\x00R\x10errorDescription\x12>\n" +
	"\apayload\x18\x04 \x01(\v2\".iot.backend.proto.ResponsePayloadH\x00R\apayloadB\t\n" +
	"\adetailsb\x06proto3"

var (
	file_response_proto_rawDescOnce sync.Once
	file_response_proto_rawDescData []byte
)

func file_response_proto_rawDescGZIP() []byte {
	file_response_proto_rawDescOnce.Do(func() {
		file_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)))
	})
	return file_response_proto_rawDescData
}

var file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_proto_goTypes = []any{
	(*Response)(nil),         // 0: iot.backend.proto.Response
	(ResultCode)(0),          // 1: iot.backend.proto.ResultCode
	(*ErrorDescription)(nil), // 2: iot.backend.proto.ErrorDescription
	(*ResponsePayload)(nil),  // 3: iot.backend.proto.ResponsePayload
}
var file_response_proto_depIdxs = []int32{
	1, // 0: iot.backend.proto.Response.result:type_name -> iot.backend.proto.ResultCode
	2, // 1: iot.backend.proto.Response.error_description:type_name -> iot.backend.proto.ErrorDescription
	3, // 2: iot.backend.proto.Response.payload:type_name -> iot.backend.proto.ResponsePayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_response_proto_init() }
func file_response_proto_init() {
	if File_response_proto != nil {
		return
	}
	file_error_proto_init()
	file_response_payload_proto_init()
	file_response_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_ErrorDescription)(nil),
		(*Response_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_proto_goTypes,
		DependencyIndexes: file_response_proto_depIdxs,
		MessageInfos:      file_response_proto_msgTypes,
	}.Build()
	File_response_proto = out.File
	file_response_proto_goTypes = nil
	file_response_proto_depIdxs = nil
}
