// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: telemetry_payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPayload struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	BatteryLevel   *uint32                    `protobuf:"varint,1,opt,name=battery_level,json=batteryLevel,proto3,oneof" json:"battery_level,omitempty"`                                       // Battery level, %%
	SpeedKmh       *float32                   `protobuf:"fixed32,2,opt,name=speed_kmh,json=speedKmh,proto3,oneof" json:"speed_kmh,omitempty"`                                                  // Current device speed, km/h
	Location       *TelemetryPayload_Location `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`                                                                    // Current bike position
	Voltage        *uint32                    `protobuf:"varint,4,opt,name=voltage,proto3,oneof" json:"voltage,omitempty"`                                                                     // Current internal voltage, V * 100
	GsmSignalLevel *uint32                    `protobuf:"varint,5,opt,name=gsm_signal_level,json=gsmSignalLevel,proto3,oneof" json:"gsm_signal_level,omitempty"`                               // Level of GSM signal, %%
	Charging       *bool                      `protobuf:"varint,6,opt,name=charging,proto3,oneof" json:"charging,omitempty"`                                                                   // Charging / not charging
	Locked         *bool                      `protobuf:"varint,7,opt,name=locked,proto3,oneof" json:"locked,omitempty"`                                                                       // Locked / Unlocked
	Sensors        map[string]string          `protobuf:"bytes,15,rep,name=sensors,proto3" json:"sensors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Other sensors
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_telemetry_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_telemetry_payload_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPayload) GetBatteryLevel() uint32 {
	if x != nil && x.BatteryLevel != nil {
		return *x.BatteryLevel
	}
	return 0
}

func (x *TelemetryPayload) GetSpeedKmh() float32 {
	if x != nil && x.SpeedKmh != nil {
		return *x.SpeedKmh
	}
	return 0
}

func (x *TelemetryPayload) GetLocation() *TelemetryPayload_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TelemetryPayload) GetVoltage() uint32 {
	if x != nil && x.Voltage != nil {
		return *x.Voltage
	}
	return 0
}

func (x *TelemetryPayload) GetGsmSignalLevel() uint32 {
	if x != nil && x.GsmSignalLevel != nil {
		return *x.GsmSignalLevel
	}
	return 0
}

func (x *TelemetryPayload) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

func (x *TelemetryPayload) GetLocked() bool {
	if x != nil && x.Locked != nil {
		return *x.Locked
	}
	return false
}

func (x *TelemetryPayload) GetSensors() map[string]string {
	if x != nil {
		return x.Sensors
	}
	return nil
}

type TelemetryPayload_Location struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Lat              float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon              float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	UtcTimeMs        uint64                 `protobuf:"varint,3,opt,name=utc_time_ms,json=utcTimeMs,proto3" json:"utc_time_ms,omitempty"`
	SatellitesAmount uint32                 `protobuf:"varint,4,opt,name=satellites_amount,json=satellitesAmount,proto3" json:"satellites_amount,omitempty"`
	Hdop             float32                `protobuf:"fixed32,5,opt,name=hdop,proto3" json:"hdop,omitempty"`
	AltitudeMeters   uint32                 `protobuf:"varint,6,opt,name=altitude_meters,json=altitudeMeters,proto3" json:"altitude_meters,omitempty"`
	Valid            bool                   `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
	Speed            *float32               `protobuf:"fixed32,9,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryPayload_Location) Reset() {
	*x = TelemetryPayload_Location{}
	mi := &file_telemetry_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload_Location) ProtoMessage() {}

func (x *TelemetryPayload_Location) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload_Location.ProtoReflect.Descriptor instead.
func (*TelemetryPayload_Location) Descriptor() ([]byte, []int) {
	return file_telemetry_payload_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TelemetryPayload_Location) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TelemetryPayload_Location) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TelemetryPayload_Location) GetUtcTimeMs() uint64 {
	if x != nil {
		return x.UtcTimeMs
	}
	return 0
}

func (x *TelemetryPayload_Location) GetSatellitesAmount() uint32 {
	if x != nil {
		return x.SatellitesAmount
	}
	return 0
}

func (x *TelemetryPayload_Location) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *TelemetryPayload_Location) GetAltitudeMeters() uint32 {
	if x != nil {
		return x.AltitudeMeters
	}
	return 0
}

func (x *TelemetryPayload_Location) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TelemetryPayload_Location) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

var File_telemetry_payload_proto protoreflect.FileDescriptor

const file_telemetry_payload_proto_rawDesc = "" +
	"\n" +
	"\x17telemetry_payload.proto\x12\x11iot.backend.proto\"\x9d\x06\n" +
	"\x10TelemetryPayload\x12(\n" +
	"\rbattery_level\x18\x01 \x01(\rH\x00R\fbatteryLevel\x88\x01\x01\x12 \n" +
	"\tspeed_kmh\x18\x02 \x01(\x02H\x01R\bspeedKmh\x88\x01\x01\x12M\n" +
	"\blocation\x18\x03 \x01(\v2,.iot.backend.proto.TelemetryPayload.LocationH\x02R\blocation\x88\x01\x01\x12\x1d\n" +
	"\avoltage\x18\x04 \x01(\rH\x03R\avoltage\x88\x01\x01\x12-\n" +
	"\x10gsm_signal_level\x18\x05 \x01(\rH\x04R\x0egsmSignalLevel\x88\x01\x01\x12\x1f\n" +
	"\bcharging\x18\x06 \x01(\bH\x05R\bcharging\x88\x01\x01\x12\x1b\n" +
	"\x06locked\x18\a \x01(\bH\x06R\x06locked\x88\x01\x01\x12J\n" +
	"\asensors\x18\x0f \x03(\v20.iot.backend.proto.TelemetryPayload.SensorsEntryR\asensors\x1a\xf3\x01\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\x12\x1e\n" +
	"\vutc_time_ms\x18\x03 \x01(\x04R\tutcTimeMs\x12+\n" +
	"\x11satellites_amount\x18\x04 \x01(\rR\x10satellitesAmount\x12\x12\n" +
	"\x04hdop\x18\x05 \x01(\x02R\x04hdop\x12'\n" +
	"\x0faltitude_meters\x18\x06 \x01(\rR\x0ealtitudeMeters\x12\x14\n" +
	"\x05valid\x18\b \x01(\bR\x05valid\x12\x19\n" +
	"\x05speed\x18\t \x01(\x02H\x00R\x05speed\x88\x01\x01B\b\n" +
	"\x06_speed\x1a:\n" +
	"\fSensorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_battery_levelB\f\n" +
	"\n" +
	"_speed_kmhB\v\n" +
	"\t_locationB\n" +
	"\n" +
	"\b_voltageB\x13\n" +
	"\x11_gsm_signal_levelB\v\n" +
	"\t_chargingB\t\n" +
	"\a_lockedb\x06proto3"

var (
	file_telemetry_payload_proto_rawDescOnce sync.Once
	file_telemetry_payload_proto_rawDescData []byte
)

func file_telemetry_payload_proto_rawDescGZIP() []byte {
	file_telemetry_payload_proto_rawDescOnce.Do(func() {
		file_telemetry_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_payload_proto_rawDesc), len(file_telemetry_payload_proto_rawDesc)))
	})
	return file_telemetry_payload_proto_rawDescData
}

var file_telemetry_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_telemetry_payload_proto_goTypes = []any{
	(*TelemetryPayload)(nil),          // 0: iot.backend.proto.TelemetryPayload
	(*TelemetryPayload_Location)(nil), // 1: iot.backend.proto.TelemetryPayload.Location
	nil,                               // 2: iot.backend.proto.TelemetryPayload.SensorsEntry
}
var file_telemetry_payload_proto_depIdxs = []int32{
	1, // 0: iot.backend.proto.TelemetryPayload.location:type_name -> iot.backend.proto.TelemetryPayload.Location
	2, // 1: iot.backend.proto.TelemetryPayload.sensors:type_name -> iot.backend.proto.TelemetryPayload.SensorsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_telemetry_payload_proto_init() }
func file_telemetry_payload_proto_init() {
	if File_telemetry_payload_proto != nil {
		return
	}
	file_telemetry_payload_proto_msgTypes[0].OneofWrappers = []any{}
	file_telemetry_payload_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_payload_proto_rawDesc), len(file_telemetry_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_payload_proto_goTypes,
		DependencyIndexes: file_telemetry_payload_proto_depIdxs,
		MessageInfos:      file_telemetry_payload_proto_msgTypes,
	}.Build()
	File_telemetry_payload_proto = out.File
	file_telemetry_payload_proto_goTypes = nil
	file_telemetry_payload_proto_depIdxs = nil
}
